config_id = "secpar_0_height_2.params.toml"
target_secpar = 120
crt_depth = 2
crt_bits = 17
ring_dimension = 4
knapsack_size = 31
e_b_sigma = 0.0
trapdoor_sigma = 4.578
base_bits = 10
p_moduli_bits = 6
scale = 4
arith_input_size = 2
arith_height = 1
