config_id = "secpar_20_height_1_p_6.params.toml"
target_secpar = 20
crt_depth = 9
crt_bits = 24
ring_dimension = 4096
knapsack_size = 28
e_b_sigma = 4.0
trapdoor_sigma = 4.578
base_bits = 8
p_moduli_bits = 6
scale = 64
arith_input_size = 2
arith_height = 1
